wandb_version: 1

init_from:
  desc: null
  value: resume
out_dir:
  desc: null
  value: out2/division_plain
start:
  desc: null
  value: '

    '
num_samples:
  desc: null
  value: 1
max_new_tokens:
  desc: null
  value: 4
temperature:
  desc: null
  value: 0.8
top_k:
  desc: null
  value: 200
seed:
  desc: null
  value: 1337
device:
  desc: null
  value: cpu
dtype:
  desc: null
  value: float16
compile:
  desc: null
  value: false
ckpt_path_name:
  desc: null
  value: ckpt_final.pt
dataset:
  desc: null
  value: bal
batch_size:
  desc: null
  value: 64
num_digit:
  desc: null
  value: 3
analyze:
  desc: null
  value: false
reverse_ab:
  desc: null
  value: false
reverse_c:
  desc: null
  value: false
zero_pad:
  desc: null
  value: false
algo_reason:
  desc: null
  value: false
verbose:
  desc: null
  value: true
add_space:
  desc: null
  value: false
verbose_correct:
  desc: null
  value: false
eps:
  desc: null
  value: 0.0
simple:
  desc: null
  value: false
random_A:
  desc: null
  value: false
random_C:
  desc: null
  value: false
prompt_overall:
  desc: null
  value: FILE:/Users/karansampath/Documents/GitHub/teaching_arithmetic_division/data/bal/train_division_7000.txt
prompt1:
  desc: null
  value: FILE:/Users/karansampath/Documents/GitHub/teaching_arithmetic_division/data/bal/train_division_3000.txt
prompt2:
  desc: null
  value: ''
prompt3:
  desc: null
  value: ''
prompt4:
  desc: null
  value: ''
wandb_log:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: karan-sampath02
wandb_project:
  desc: null
  value: division
wandb_run_name:
  desc: null
  value: eval_plain
exp_name:
  desc: null
  value: eval_plain
data_type:
  desc: null
  value: text
operator:
  desc: null
  value: /
data_format:
  desc: null
  value: plain
vocabulary:
  desc: null
  value: all_ascii_chars
meta_path_specified:
  desc: null
  value: false
data_shuffle:
  desc: null
  value: true
model_type:
  desc: null
  value: gpt2
result_dir:
  desc: null
  value: out2/division_plain/eval_plain_2
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709369913.163274
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.3
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
