add_space: false
algo_reason: false
analyze: false
batch_size: 64
ckpt_path_name: ckpt_final.pt
compile: false
data_format: plain
data_shuffle: true
data_type: text
dataset: bal
device: cpu
dtype: bfloat16
eps: 0.0
exp_name: eval_plain
init_from: resume
max_new_tokens: 4
meta_path_specified: false
model_type: gpt2
num_digit: 3
num_samples: 1
operator: /
out_dir: out2/division_plain
prompt1: FILE:/Users/karansampath/Documents/GitHub/teaching_arithmetic_division/data/bal/train_division_3000.txt
prompt2: ''
prompt3: ''
prompt4: ''
prompt_overall: FILE:/Users/karansampath/Documents/GitHub/teaching_arithmetic_division/data/bal/train_division_7000.txt
random_A: false
random_C: false
result_dir: out2/division_plain/eval_plain
reverse_ab: false
reverse_c: false
seed: 1337
simple: false
start: '

  '
temperature: 0.8
top_k: 200
verbose: true
verbose_correct: false
vocabulary: all_ascii_chars
wandb_entity: ssdd
wandb_log: true
wandb_project: division
wandb_run_name: eval_plain
zero_pad: false
